import Image from "next/image";
import classes from "./Layout.module.css";
import Logo from "../../public/logo.webp";
import Head from "next/head";
import Nickname from "../Nickname/Nickname";
import { useSession } from "next-auth/react";
import LoginButton from '../LoginButton/LoginButton';
import { useEffect } from 'react';

export default function Layout({ children }) {
  const { data: session } = useSession();

  useEffect(()=>{
    console.log(
        "%cCandidat Murphy.",
        "color:green;font-size:8px;font-family:monospace;box-shadow: 0 0 5px black"
        );
  },[]);

  return (
    <div className={classes.container}>
      <Head>
        <title>Movie Scale</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={classes.header}>
        <Image src={Logo} width={50} height={29} alt="logo" />
        {session ? <Nickname /> : <LoginButton/>}
      </header>
      <main>{children}</main>
    </div>
  );
}
